"""Renders the contract reference (docs/CONTRACTS.md) and the per-component slot listing."""

from __future__ import annotations

from uikit.contracts import Contract, ContractSet, ParamValue

PREAMBLE = """\
# Layout contracts

<!-- GENERATED by `python -m uikit docs` from contracts/*.json - do not edit by hand. -->

What a layout must contain for the kit to drive it. The server can only do two things to a
Panorama layout: write a string into a `{s:...}` text slot, and toggle a class on a panel by id.
So a layout *is* its ids, its text slots and the classes its stylesheet reacts to - everything
else (structure, colours, animation) is yours.

## Rules for every component

- **File**: `panorama/layout/custom_game/<name>.xml`. Plugins refer to it by `<name>` only.
- **Root**: the outermost panel is anonymous (the loader owns it); one level in, a panel with
  `id="<name>_root"` authored with class `hidden`. Text slots are addressed through the root id:
  deriving it from the file name keeps two layouts from sharing their text.
- **Marker**: a comment `<!-- uikit:<component> param=value -->` naming the contract and its pool
  sizes. `python -m uikit check-all` validates every layout that has one.
- **Text**: a slot is `text="{s:<var>}"` on a `<Label>`. Same names in every layout of a component -
  that is what makes a custom toast a drop-in for the bundled one.
- **Style**: `style-<name>` on the component's main panel. Define at least `style-neutral`,
  `style-info`, `style-success`, `style-warn`, `style-danger`.
- **Extra slots**: `Texts["footer"]` on any options record is written to `<prefix>_footer`, and
  `Classes` adds free classes on the main panel - for what a custom layout has and the bundled one
  does not.
- **`empty`**: optional text labels get `empty` when blank; collapse them (`visibility: collapse`).
- **Entry**: `show` is added one network update after `hidden` is removed, so a transition on `show`
  has a start state.
"""


def _format(value: ParamValue) -> str:
    if isinstance(value, list):
        return ",".join(value)
    return str(value)


def _yes_no(flag: bool) -> str:
    if flag:
        return "yes"
    return "no"


def _required_mark(flag: bool) -> str:
    if flag:
        return "*"
    return " "


def slot_table(contract: Contract) -> str:
    rows = [
        "| Element | Kind | Required | Kit writes | Meaning |",
        "|---|---|---|---|---|",
    ]
    for panel in contract.panels:
        classes = ", ".join(f"`{name}`" for name in panel.classes) or "click"
        kind = (panel.tag or "panel").lower()
        required = _yes_no(panel.required)
        rows.append(f'| `id="{panel.id}"` | {kind} | {required} | {classes} | {panel.doc} |')

    for text in contract.texts:
        required = _yes_no(text.required)
        rows.append(f'| `text="{{s:{text.var}}}"` | Label text | {required} | string | {text.doc} |')

    return "\n".join(rows)


def render_contract(contract: Contract) -> str:
    parts = [
        f"## {contract.component}",
        "",
        contract.summary,
        "",
        f"C#: `{contract.csharp}`",
        "",
        f"Marker: `<!-- {contract.marker()} -->`",
        "",
    ]
    if contract.params:
        parts += ["Pool parameters (marker and C# layout descriptor must agree):", ""]
        for param in contract.params.values():
            parts.append(f"- `{param.name}` (default `{_format(param.default)}`): {param.doc}")

        axes = ", ".join(
            f"`{{{placeholder}}}` = each of `{param}`"
            for placeholder, param in contract.repeat.items()
        )
        parts += ["", f"Placeholders: {axes}.", ""]

    classes = ", ".join(f"`.{name}`" for name in contract.css)
    parts += [
        slot_table(contract),
        "",
        f"Stylesheet should define: {classes}.",
        "",
    ]
    return "\n".join(parts)


def render_reference(contracts: ContractSet) -> str:
    return PREAMBLE + "\n" + "\n".join(render_contract(c) for c in contracts)


def render_contract_page(contract: Contract) -> str:
    """One contract, as its own page under docs/contracts/."""
    body = render_contract(contract).removeprefix(f"## {contract.component}\n\n")
    return (
        f"# {contract.component}\n\n"
        f"<!-- GENERATED by `python -m uikit docs` from contracts/{contract.component}.json"
        " - do not edit by hand. -->\n\n"
        f"{body}"
    )


def render_contracts_index(contracts: ContractSet) -> str:
    rows = ["| Contract | What the layout is |", "|---|---|"]
    rows += [f"| [{c.component}]({c.component}.md) | {c.summary} |" for c in contracts]
    return PREAMBLE + "\n" + "\n".join(rows) + "\n"


def render_slots(contract: Contract, params: dict[str, ParamValue], preview: int = 6) -> str:
    """What to put in a layout for these pool sizes, concrete ids included."""

    def sample(items: list[str]) -> str:
        text = ", ".join(items[:preview])
        if len(items) > preview:
            text += f" ... ({len(items)})"
        return text

    lines = [
        f"# {contract.component} - {contract.summary}",
        "",
        f"Marker:  <!-- {contract.marker(params)} -->",
        'Root:    <Panel id="<file name>_root" class="... hidden">',
        "",
        "Panels the kit toggles classes on:",
    ]
    for panel in contract.panels:
        flag = _required_mark(panel.required)
        ids = sample(contract.expand(panel.id, params))
        classes = " ".join(panel.classes)
        lines.append(f"  {flag} {ids}    [{classes}]")

    lines += ["", 'Text slots (on a Label, as text="{s:...}"):']
    for text in contract.texts:
        flag = _required_mark(text.required)
        slots = [f"{{s:{var}}}" for var in contract.expand(text.var, params)]
        lines.append(f"  {flag} {sample(slots)}    {text.doc}")
    lines += ["", "* = required"]
    return "\n".join(lines)
