"""Layout document assembly: header, marker, root wrapper, indentation."""

from __future__ import annotations

from dataclasses import dataclass

INDENT = "\t"


def indent(block: str, depth: int) -> str:
    """Re-indents ``block`` (written flush-left) by ``depth`` tabs, one line per line."""
    pad = INDENT * depth
    lines = []
    for line in block.strip("\n").split("\n"):
        if line:
            lines.append(f"{pad}{line}\n")
        else:
            lines.append("\n")
    return "".join(lines)


@dataclass(frozen=True)
class LayoutDocument:
    """A complete layout file: stylesheet includes, marker, description, root, body."""

    name: str
    """File name without extension; the root panel id is ``<name>_root``."""
    stylesheet: str
    """Stylesheet name without extension, included after uikit_shared."""
    marker: str
    description: str
    body: str
    """Content of the root panel, flush-left; indented on render."""
    generated_by: str = "python -m uikit generate"

    def render(self) -> str:
        description = indent(self.description, 2).rstrip("\n")
        return f"""<root>
	<styles>
		<include src="s2r://panorama/styles/custom_game/uikit_shared.vcss_c" />
		<include src="s2r://panorama/styles/custom_game/{self.stylesheet}.vcss_c" />
	</styles>

	<!-- {self.marker} -->
	<!--
		GENERATED by `{self.generated_by}`.
{description}

		Slot reference: docs/CONTRACTS.md, or `python -m uikit slots <component>`.
		Root authored hidden: a custom_hud_layout is shown to every player; per-player state only overlays.
	-->
	<Panel class="uikit-screen" hittest="false">
		<Panel id="{self.name}_root" class="uikit-fill hidden" hittest="false">
{indent(self.body, 3)}		</Panel>
	</Panel>
</root>
"""
